namespace SmartValley.Domain.Exceptions
{
    public enum ErrorCode
    {
        EtherAlreadySent,
        ServerError,
        ValidatationError,
        ProjectNotFound,
        EmailAlreadyExists,
        InvalidSignature,
        EmailNotConfirmed,
        IncorrectData,
        EmailAlreadySent,
        UserNotFound,
        RoleNotFound,
        UserHaveNoRole,
        EmailSendingFailed,
        InvalidFileUploaded,
        AddressAlreadyExists,
        ExpertApplicationAlreadyProcessed,
        ShouldCheckAreasToAccept,
        AcceptedOfferNotFound,
        PendingOffersNotFound,
        AuthenticationError,
        ExpertNotFound,
        CountryNotFound,
        ProjectCouldntBeRemoved,
        ProjectScoringApplicationNotFound,
        ScoringApplicationAlreadySubmitted,
        UserNotAuthor,
        TeamMemberNotFound
    }
}