import {MultiTranslateLoader} from './multi-translate-loader';

export function multiTranslateLoaderFactory() {
  return new MultiTranslateLoader([
    'services/questions/questions',
    'services/authentication/authentication-service',
    'services/balance/balance-service',
    'services/translate/common',
    'services/voting/voting-service',
    'components/header/header.component',
    'components/application/application.component',
    'components/my-projects/my-projects.component',
    'components/landing/landing.component',
    'components/voting/voting.component',
    'components/admin-panel/admin-panel.component',
    'components/admin-panel/admin-expert-applications-list/admin-expert-applications-list.component',
    'components/admin-panel/admin-expert-application/admin-expert-application.component',
    'components/admin-panel/admin-scoring-projects/admin-scoring-project.component',
    'components/expert-status/expert-status.component',
    'components/scoring/scoring.component',
    'components/register-expert/register-expert.component',
    'components/estimate/estimate.component',
    'components/report/report.component',
    'components/voting-card/voting-card.component',
    'components/report/questions/questions.component',
    'components/footer/footer.component',
    'components/common/project-card/project-card.component',
    'components/common/transaction-awaiting-modal/transaction-awaiting-modal.component',
    'components/common/receive-ether-modal/receive-ether-modal.component',
    'components/common/project-information/project-information.component',
    'components/account/account.component',
    'components/common/free-scoring-confirmation-modal/free-scoring-confirmation-modal.component',
    'components/common/vote-modal/vote-modal.component',
    'components/common/register-modal/register-modal.component',
    'components/common/change-email-modal/change-email-modal.component',
    'components/common/confirm-email/confirm-email.component',
    'components/common/confirm-email/confirm-email-modal.component',
    'components/completed-voting/completed-voting.component',
    'components/common/create-new-expert-modal/create-new-expert-modal.component',
    'components/admin-panel/admin-experts-list/admin-expert-list.component',
    'components/common/edit-expert-modal/edit-expert-modal.component',
    'components/common/experts-count-selection-modal/experts-count-selection-modal.component',
    'components/expert/expert.component',
    'components/expert/expert-work-place/expert-work-place.component',
    'components/expert/expert-offers/expert-offers.component',
    'components/expert/expert-offers-history/expert-offers-history.component'
  ]);
}
